language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

env:
  matrix:
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=^6.0
    - LARAVEL=^7.0
    - LARAVEL=^8.0

matrix:
    exclude:
        - php: 7.1
          env: LARAVEL=^6.0
    allow_failures:
        - php: hhvm

install: travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - travis_retry php vendor/bin/coveralls -v

notifications:
  slack: red-creek:5lI8ybvl6YTcCNPosh4TE13h
